#dbUserPasswords:
#  dbuserPassword: ""

databases:
  mosip_toolkit:
    enabled: true
    host: "postgres-postgresql.postgres"
    port: 5432
    su:
      user: postgres
      secret:
        name: postgres-postgresql
        key: postgres-password
    dml: 0
    branch: develop
